// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:3091' | (string & {});
};

export type GetIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type PostAccountSetPasswordData = {
    body: {
        newPassword: string;
    };
    path?: never;
    query?: never;
    url: '/account/set-password';
};

export type PostAccountAvatarData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/account/avatar';
};

export type GetAccountAvatarUrlData = {
    body?: never;
    path?: never;
    query: {
        key: string;
    };
    url: '/account/avatar-url';
};

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};
