// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Composable, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetAccountAvatarUrlData, GetCompaniesByCompanyIdLogoUrlData, GetCompaniesByCompanyIdLogoUrlError, GetCompaniesByCompanyIdLogoUrlResponse, GetCompaniesBySlugBySlugData, GetCompaniesBySlugBySlugError, GetCompaniesBySlugBySlugResponse, GetCompaniesData, GetCompaniesResponse, GetIndexData, GetMeData, PostAccountAvatarData, PostAccountSetPasswordData, PostCompaniesByCompanyIdLogoData, PostCompaniesByCompanyIdLogoError, PostCompaniesByCompanyIdLogoResponse, PostCompaniesData, PostCompaniesError, PostCompaniesResponse } from './types.gen';

export type Options<TComposable extends Composable = '$fetch', TData extends TDataShape = TDataShape, ResT = unknown, DefaultT = undefined> = Options2<TComposable, TData, ResT, DefaultT> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 *
 * Returns API availability status.
 */
export const getIndex = <TComposable extends Composable = '$fetch', DefaultT = undefined>(options: Options<TComposable, GetIndexData, unknown, DefaultT>) => (options.client ?? client).get<TComposable, unknown | DefaultT, unknown, DefaultT>({ url: '/', ...options });

/**
 * Set password for authenticated user
 *
 * Sets initial password for users without credential account. Requires an active session.
 */
export const postAccountSetPassword = <TComposable extends Composable = '$fetch', DefaultT = undefined>(options: Options<TComposable, PostAccountSetPasswordData, unknown, DefaultT>) => (options.client ?? client).post<TComposable, unknown | DefaultT, unknown, DefaultT>({
    url: '/account/set-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Upload avatar to Cloudflare R2
 *
 * Uploads user avatar and returns public URL.
 */
export const postAccountAvatar = <TComposable extends Composable = '$fetch', DefaultT = undefined>(options: Options<TComposable, PostAccountAvatarData, unknown, DefaultT>) => (options.client ?? client).post<TComposable, unknown | DefaultT, unknown, DefaultT>({
    url: '/account/avatar',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get signed URL for stored avatar key
 *
 * Returns time-limited signed URL for a private avatar object.
 */
export const getAccountAvatarUrl = <TComposable extends Composable = '$fetch', DefaultT = undefined>(options: Options<TComposable, GetAccountAvatarUrlData, unknown, DefaultT>) => (options.client ?? client).get<TComposable, unknown | DefaultT, unknown, DefaultT>({ url: '/account/avatar-url', ...options });

/**
 * List companies for current user
 *
 * Returns companies the authenticated user belongs to, with membership role.
 */
export const getCompanies = <TComposable extends Composable = '$fetch', DefaultT extends GetCompaniesResponse = GetCompaniesResponse>(options: Options<TComposable, GetCompaniesData, GetCompaniesResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetCompaniesResponse | DefaultT, unknown, DefaultT>({ url: '/companies/', ...options });

/**
 * Create company
 *
 * Creates a company and adds the current user as owner.
 */
export const postCompanies = <TComposable extends Composable = '$fetch', DefaultT extends PostCompaniesResponse = PostCompaniesResponse>(options: Options<TComposable, PostCompaniesData, PostCompaniesResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostCompaniesResponse | DefaultT, PostCompaniesError, DefaultT>({
    url: '/companies/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get company by slug
 *
 * Returns a company the user belongs to, matched by URL slug.
 */
export const getCompaniesBySlugBySlug = <TComposable extends Composable = '$fetch', DefaultT extends GetCompaniesBySlugBySlugResponse = GetCompaniesBySlugBySlugResponse>(options: Options<TComposable, GetCompaniesBySlugBySlugData, GetCompaniesBySlugBySlugResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetCompaniesBySlugBySlugResponse | DefaultT, GetCompaniesBySlugBySlugError, DefaultT>({ url: '/companies/by-slug/{slug}', ...options });

/**
 * Upload company logo
 *
 * Uploads a logo image for a company. Requires owner or admin role.
 */
export const postCompaniesByCompanyIdLogo = <TComposable extends Composable = '$fetch', DefaultT extends PostCompaniesByCompanyIdLogoResponse = PostCompaniesByCompanyIdLogoResponse>(options: Options<TComposable, PostCompaniesByCompanyIdLogoData, PostCompaniesByCompanyIdLogoResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostCompaniesByCompanyIdLogoResponse | DefaultT, PostCompaniesByCompanyIdLogoError, DefaultT>({
    url: '/companies/{companyId}/logo',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get signed URL for company logo
 *
 * Returns a time-limited signed URL for the company's stored logo.
 */
export const getCompaniesByCompanyIdLogoUrl = <TComposable extends Composable = '$fetch', DefaultT extends GetCompaniesByCompanyIdLogoUrlResponse = GetCompaniesByCompanyIdLogoUrlResponse>(options: Options<TComposable, GetCompaniesByCompanyIdLogoUrlData, GetCompaniesByCompanyIdLogoUrlResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetCompaniesByCompanyIdLogoUrlResponse | DefaultT, GetCompaniesByCompanyIdLogoUrlError, DefaultT>({ url: '/companies/{companyId}/logo-url', ...options });

/**
 * Get current user
 *
 * Returns the authenticated user (requires session).
 */
export const getMe = <TComposable extends Composable = '$fetch', DefaultT = undefined>(options: Options<TComposable, GetMeData, unknown, DefaultT>) => (options.client ?? client).get<TComposable, unknown | DefaultT, unknown, DefaultT>({ url: '/me', ...options });
