// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:3091' | (string & {});
};

export type GetIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type PostAccountSetPasswordData = {
    body: {
        newPassword: string;
    };
    path?: never;
    query?: never;
    url: '/account/set-password';
};

export type PostAccountAvatarData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/account/avatar';
};

export type GetAccountAvatarUrlData = {
    body?: never;
    path?: never;
    query: {
        key: string;
    };
    url: '/account/avatar-url';
};

export type GetCompaniesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/companies/';
};

export type GetCompaniesResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        name: string;
        role: 'owner' | 'admin' | 'member' | 'viewer';
    }>;
};

export type GetCompaniesResponse = GetCompaniesResponses[keyof GetCompaniesResponses];

export type PostCompaniesData = {
    body: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/companies/';
};

export type PostCompaniesErrors = {
    /**
     * Response for status 500
     */
    500: {
        message: string;
    };
};

export type PostCompaniesError = PostCompaniesErrors[keyof PostCompaniesErrors];

export type PostCompaniesResponses = {
    /**
     * UserCompany
     *
     * Response for status 200
     */
    200: {
        id: string;
        name: string;
        role: 'owner' | 'admin' | 'member' | 'viewer';
    };
};

export type PostCompaniesResponse = PostCompaniesResponses[keyof PostCompaniesResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};
