// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:3091' | (string & {});
};

export type GetIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type PostAccountSetPasswordData = {
    body: {
        newPassword: string;
    };
    path?: never;
    query?: never;
    url: '/account/set-password';
};

export type PostAccountAvatarData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/account/avatar';
};

export type GetAccountAvatarUrlData = {
    body?: never;
    path?: never;
    query: {
        key: string;
    };
    url: '/account/avatar-url';
};

export type GetCompaniesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/companies/';
};

export type GetCompaniesResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        name: string;
        slug: string;
        role: 'owner' | 'admin' | 'member' | 'viewer';
        logoKey: string | unknown;
        logoUrl: string | unknown;
    }>;
};

export type GetCompaniesResponse = GetCompaniesResponses[keyof GetCompaniesResponses];

export type PostCompaniesData = {
    body: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/companies/';
};

export type PostCompaniesErrors = {
    /**
     * Response for status 500
     */
    500: {
        message: string;
    };
};

export type PostCompaniesError = PostCompaniesErrors[keyof PostCompaniesErrors];

export type PostCompaniesResponses = {
    /**
     * UserCompany
     *
     * Response for status 200
     */
    200: {
        id: string;
        name: string;
        slug: string;
        role: 'owner' | 'admin' | 'member' | 'viewer';
        logoKey: string | unknown;
        logoUrl: string | unknown;
    };
};

export type PostCompaniesResponse = PostCompaniesResponses[keyof PostCompaniesResponses];

export type GetCompaniesBySlugBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/companies/by-slug/{slug}';
};

export type GetCompaniesBySlugBySlugErrors = {
    /**
     * Response for status 404
     */
    404: {
        message: string;
    };
};

export type GetCompaniesBySlugBySlugError = GetCompaniesBySlugBySlugErrors[keyof GetCompaniesBySlugBySlugErrors];

export type GetCompaniesBySlugBySlugResponses = {
    /**
     * UserCompany
     *
     * Response for status 200
     */
    200: {
        id: string;
        name: string;
        slug: string;
        role: 'owner' | 'admin' | 'member' | 'viewer';
        logoKey: string | unknown;
        logoUrl: string | unknown;
    };
};

export type GetCompaniesBySlugBySlugResponse = GetCompaniesBySlugBySlugResponses[keyof GetCompaniesBySlugBySlugResponses];

export type PostCompaniesByCompanyIdLogoData = {
    body: {
        file: Blob | File;
    };
    path: {
        companyId: string;
    };
    query?: never;
    url: '/companies/{companyId}/logo';
};

export type PostCompaniesByCompanyIdLogoErrors = {
    /**
     * Response for status 400
     */
    400: {
        message: string;
    };
    /**
     * Response for status 403
     */
    403: {
        message: string;
    };
    /**
     * Response for status 404
     */
    404: {
        message: string;
    };
    /**
     * Response for status 500
     */
    500: {
        message: string;
    };
};

export type PostCompaniesByCompanyIdLogoError = PostCompaniesByCompanyIdLogoErrors[keyof PostCompaniesByCompanyIdLogoErrors];

export type PostCompaniesByCompanyIdLogoResponses = {
    /**
     * UserCompany
     *
     * Response for status 200
     */
    200: {
        id: string;
        name: string;
        slug: string;
        role: 'owner' | 'admin' | 'member' | 'viewer';
        logoKey: string | unknown;
        logoUrl: string | unknown;
    };
};

export type PostCompaniesByCompanyIdLogoResponse = PostCompaniesByCompanyIdLogoResponses[keyof PostCompaniesByCompanyIdLogoResponses];

export type GetCompaniesByCompanyIdLogoUrlData = {
    body?: never;
    path: {
        companyId: string;
    };
    query: {
        key: string;
    };
    url: '/companies/{companyId}/logo-url';
};

export type GetCompaniesByCompanyIdLogoUrlErrors = {
    /**
     * Response for status 403
     */
    403: {
        message: string;
    };
    /**
     * Response for status 500
     */
    500: {
        message: string;
    };
};

export type GetCompaniesByCompanyIdLogoUrlError = GetCompaniesByCompanyIdLogoUrlErrors[keyof GetCompaniesByCompanyIdLogoUrlErrors];

export type GetCompaniesByCompanyIdLogoUrlResponses = {
    /**
     * Response for status 200
     */
    200: {
        url: string;
    };
};

export type GetCompaniesByCompanyIdLogoUrlResponse = GetCompaniesByCompanyIdLogoUrlResponses[keyof GetCompaniesByCompanyIdLogoUrlResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};
